[package]
name = "compact_sequence"
version = "0.4.1"
edition = "2021"

[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"

[dependencies]
walkdir = "2.3"
rayon = "1.5"
lazy_static = "1.4"
structopt = "0.3"

[dev-dependencies]
tempfile = "3.2.0"